#!/usr/bin/env bash
set -Eeuo pipefail
cd /opt/litesoup

# Pre-req: stack already installed (run 01 first if not)
systemctl is-active --quiet apache2 || bash install/install-stack.sh

# Map example.test -> 127.0.0.1 inside container
grep -q 'example.test' /etc/hosts || echo '127.0.0.1 example.test' >>/etc/hosts

bash site/site-create.sh --domain=example.test

# Apache must reload + serve the site
ss -ltn | grep -E ':80\b' >/dev/null
curl -sS --max-time 10 -H 'Host: example.test' -o /tmp/wp-install.html http://127.0.0.1/wp-admin/install.php
grep -qE 'WordPress|Select a default language|wp-admin' /tmp/wp-install.html
rm -f /tmp/wp-install.html

# Assert DB + user exist
db=$(mysql --defaults-file=/root/.litesoup-mariadb-root -Nse \
  "SELECT SCHEMA_NAME FROM information_schema.SCHEMATA WHERE SCHEMA_NAME LIKE 'wp_example_test%';")
[ -n "${db}" ]

# Assert docroot path + ownership match the per-user model
[ -f /home/litesoup/webapps/example.test/wp-config.php ]
[ "$(stat -c '%U:%G' /home/litesoup/webapps/example.test)" = "litesoup:litesoup" ]
[ "$(stat -c '%U:%G' /home/litesoup/webapps/example.test/wp-config.php)" = "litesoup:litesoup" ]

# PHP-FPM socket the vhost points to actually exists and is owned correctly
[ -S /run/php/litesoup-php8.2-fpm.sock ]

# --- Plan I.F: WP_CACHE_KEY_SALT + WP_REDIS_* injection ---

WP1=/home/litesoup/webapps/example.test
salt1="$(sudo -H -u litesoup wp --path="${WP1}" config get WP_CACHE_KEY_SALT --type=constant)"
# Salt may be generated by wp-cli 2.12+ itself (full WP secret-key alphabet,
# higher entropy) OR by site-create.sh's inject_cache_constants fallback
# (64-char hex). Accept either: assert non-empty + reasonable length.
[ -n "${salt1}" ] || { echo "FAIL: WP_CACHE_KEY_SALT empty" >&2; exit 1; }
[ "${#salt1}" -ge 32 ] || { echo "FAIL: WP_CACHE_KEY_SALT too short (${#salt1} chars): ${salt1}" >&2; exit 1; }

# WP_REDIS_* constants present and match what install-stack wrote
[ "$(sudo -H -u litesoup wp --path="${WP1}" config get WP_REDIS_HOST     --type=constant)" = "127.0.0.1" ]
[ "$(sudo -H -u litesoup wp --path="${WP1}" config get WP_REDIS_PORT     --type=constant)" = "6379" ]
[ "$(sudo -H -u litesoup wp --path="${WP1}" config get WP_REDIS_DATABASE --type=constant)" = "0" ]
WP_REDIS_PW="$(sudo -H -u litesoup wp --path="${WP1}" config get WP_REDIS_PASSWORD --type=constant)"
ENV_REDIS_PW="$(. /etc/litesoup/redis.env && printf '%s' "${REDIS_PASSWORD}")"
[ "${WP_REDIS_PW}" = "${ENV_REDIS_PW}" ] \
  || { echo "FAIL: WP_REDIS_PASSWORD does not match /etc/litesoup/redis.env" >&2; exit 1; }

# Second site: salt must differ (the actual multi-tenant security property)
grep -q 'second.test' /etc/hosts || echo '127.0.0.1 second.test' >>/etc/hosts
bash site/site-create.sh --domain=second.test
WP2=/home/litesoup/webapps/second.test
salt2="$(sudo -H -u litesoup wp --path="${WP2}" config get WP_CACHE_KEY_SALT --type=constant)"
[ -n "${salt2}" ]                || { echo "FAIL: second salt empty" >&2; exit 1; }
[ "${#salt2}" -ge 32 ]           || { echo "FAIL: second salt too short (${#salt2} chars)" >&2; exit 1; }
[ "${salt1}" != "${salt2}" ]     || { echo "FAIL: two sites got the same WP_CACHE_KEY_SALT" >&2; exit 1; }

# Re-run for idempotency (CREATE DATABASE IF NOT EXISTS + CREATE USER IF NOT EXISTS
# + ensure_user/ensure_pool no-ops; wp config create will fail on existing
# wp-config.php which is the desired guard. The `|| true` allows the script
# to exit non-zero on the WP step without failing the test.)
bash site/site-create.sh --domain=example.test || true

# Salt must NOT have rotated on re-run -- live caches would be invalidated.
salt1_after="$(sudo -H -u litesoup wp --path="${WP1}" config get WP_CACHE_KEY_SALT --type=constant)"
[ "${salt1}" = "${salt1_after}" ] \
  || { echo "FAIL: WP_CACHE_KEY_SALT rotated on site-create.sh re-run" >&2; exit 1; }

echo "02_site_create: PASS"
